version: '3'
services:
  redis:
    image: redis
  app:
    build: .
    command: bundle exec ruby app.rb
    volumes:
      - .:/impraise-shorty
    ports:
      - "4567:4567"
    depends_on:
      - redis
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379/0